# Assignment 2 \
 Name:Nathan Starkman \
 Student Number: 1127811 \
 Date: October 21st, 2022 \


both: q1 q2

q1: q1.c
	gcc -Wall -pedantic q1.c -o q1

q2: q2.c
	gcc -Wall -pedantic q2.c -o q2

clean:
	rm -rf *o q1 q2